[package]
name = "smartparse-core"
version = "0.1.0"
authors = ["Darren Tsung <darren.tsung@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.48"

[dev-dependencies]
serde = "1.0"
serde_derive = "1.0"
toml = "0.5.6"